apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: devops-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  serviceName: "postgres-service"
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD

        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER

        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB

        # Variable d'environnement pour spécifier le chemin de stockage des données de PostgreSQL
        #C'est le branchement du pods vers l'emplacement du disque dur
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
          
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data

        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"

  #Machine a fabiruqer des volumes persistants pour stocker les données de la base de données
  #C'est la commande pour fabriquer le disque
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
      namespace: devops-lab
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: standard
      resources:
        requests:
          storage: 1Gi

